extends Reference

const MDX_MODEL = 'MDLX'

# MDX MODEL SUB-CHUNKS
const VERSION = 'VERS'
const GEOSET = 'GEOS'
const TEXTURE = 'TEXS'
const MATERIAL = 'MTLS'
const MODEL = 'MODL'
const BONE = 'BONE'
const PIVOT_POINT = 'PIVT'
const HELPER = 'HELP'
const ATTACHMENT = 'ATCH'
const EVENT_OBJECT = 'EVTS'
const COLLISION_SHAPE = 'CLID'
const SEQUENCE = 'SEQS'
const GEOSET_ANIMATION = 'GEOA'

const LAYER = 'LAYS'

const MODEL_CHILD = [
	VERSION,
	GEOSET,
	TEXTURE,
	MATERIAL,
	MODEL,
	BONE,
	PIVOT_POINT,
	HELPER,
	ATTACHMENT,
	EVENT_OBJECT,
	COLLISION_SHAPE,
	SEQUENCE,
	GEOSET_ANIMATION,
	"GLBS",
	"PRE2",
	"RIBB",
]

# LAYER SUB-CHUNKS
const MATERIAL_TEXTURE_ID = 'KMTF'
const MATERIAL_ALPHA = 'KMTA'
const MATERIAL_EMISSIONS = 'KMTE'
const MATERIAL_FRESNEL_COLOR = 'KFC3'
const MATERIAL_FRESNEL_ALPHA = 'KFCA'
const MATERIAL_FRESNEL_TEAMCOLOR = 'KFTC'

const LAYER_CHILD = [
	MATERIAL_TEXTURE_ID,
	MATERIAL_ALPHA,
	MATERIAL_EMISSIONS,
	MATERIAL_FRESNEL_COLOR,
	MATERIAL_FRESNEL_ALPHA,
	MATERIAL_FRESNEL_TEAMCOLOR
]

const INTERPOLATION_TYPE_LINEAR = 1
