const MdxUtils = preload("../mdx/MdxUtils.gd")

const MdxBoneParser = preload("../mdx/MdxBoneParser.gd")
const MdxGeosetParser = preload("../mdx/MdxGeosetParser.gd")
const MdxLayerParser = preload("../mdx/MdxLayerParser.gd")
const MdxMaterialParser = preload("../mdx/MdxMaterialParser.gd")
const MdxModelParser = preload("../mdx/MdxModelParser.gd")
const MdxPivotPointParser = preload("../mdx/MdxPivotPointParser.gd")
const MdxSequenceParser = preload("../mdx/MdxSequenceParser.gd")
const MdxTextureParser = preload("../mdx/MdxTextureParser.gd")

const War3Bone = preload("../types/War3Bone.gd")
const War3Geoset = preload("../types/War3Geoset.gd")
const War3Info = preload("../types/War3Info.gd")
const War3Layer = preload("../types/War3Layer.gd")
const War3Material = preload("../types/War3Material.gd")
const War3Model = preload("../types/War3Model.gd")
const War3Node = preload("../types/War3Node.gd")
const War3RotationTrack = preload("../types/War3RotationTrack.gd")
const War3Sequence = preload("../types/War3Sequence.gd")
const War3Texture = preload("../types/War3Texture.gd")
const War3VectorTrack = preload("../types/War3VectorTrack.gd")

const MdxParser = preload("../mdx/MdxParser.gd")

const War3AnimationBuilder = preload("../builders/War3AnimationBuilder.gd")
const War3MaterialBuilder = preload("../builders/War3MaterialBuilder.gd")
const War3MeshBuilder = preload("../builders/War3MeshBuilder.gd")
const War3MeshInstanceBuilder = preload("../builders/War3MeshInstanceBuilder.gd")
const War3SkeletonBuilder = preload("../builders/War3SkeletonBuilder.gd")
const War3SkinBuilder = preload("../builders/War3SkinBuilder.gd")
const War3TextureBuilder = preload("../builders/War3TextureBuilder.gd")
